services:
  postgres:
    image: postgres:15-alpine
    container_name: eka_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eka_admin
      POSTGRES_PASSWORD: eka_secure_dev_pass_2026
      POSTGRES_DB: eka_id
    ports:
      - "5433:5432"
    volumes:
      - eka_pgdata:/var/lib/postgresql/data
      - ./database/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seeds/dev_seeds.sql:/docker-entrypoint-initdb.d/02_seeds.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eka_admin -d eka_id"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: eka_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - eka_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    image: eka_api:latest
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: eka_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ENVIRONMENT: development
      SERVER_PORT: "8080"
      SERVER_HOST: "0.0.0.0"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: eka_admin
      DB_PASSWORD: eka_secure_dev_pass_2026
      DB_NAME: eka_id
      DB_SSL_MODE: disable
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      JWT_SECRET: eka_jwt_dev_super_secret_signing_key_32bytes_minimum_length_2026
      VERIFY_URL_PREFIX: "http://localhost:3000/verify"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
    ports:
      - "8080:8080"

  web:
    image: eka_web:latest
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: eka_web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:3000"

volumes:
  eka_pgdata:
  eka_redisdata: